apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap.yaml
  - httproute.yaml

images:
  - name: ghcr.io/back1ash/issuebell
    newTag: sha-0802161aa4f11a65326b5673235ec1c428a3c447
