apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap.yaml
  - httproute.yaml

images:
  - name: ghcr.io/back1ash/issuebell
    newTag: sha-8cd60e78beda5ee497cbc8c89d58ac5641fd167f
