apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap.yaml
  - httproute.yaml

images:
  - name: ghcr.io/back1ash/issuebell
    newTag: sha-414dce7f4eda89a61ae0a431bc93a851e8b94612
